### ISSUE TITLE
Static IP address

### ISSUE THREAD

**Issue by waghih** [CytronTechnologies/CytronWiFiShield#1]
https://github.com/CytronTechnologies/CytronWiFiShield/blob/24e6667b0041b450370f5bdac1b10a08358316d8/examples/WiFiSoftAP/WiFiSoftAP.ino#L67

Is there any way to config the softAPIP to static IP address instead of DCHP?

**Comment by bengchet** [comment]
Hi, by default it is bind to 192.168.4.1. It is static IP address.

**Comment by waghih** [comment]
@bengchet thanks 👍
